CREATE TABLE epigram (
    id SERIAL PRIMARY KEY,
    quote character varying(255) NOT NULL UNIQUE,
    author character varying(255) NOT NULL
);

INSERT INTO epigram (id, quote, author) VALUES 
(1, 'A copy of the universe is not what is required of art; one of the damned things is ample.', 'Rebecca West'),
(2, 'A critic is a bundle of biases held loosely together by a sense of taste.', 'Whitney Balliett'),
(3, 'A team effort is a lot of people doing what I say.', 'Michael Winner'),
(4, 'A writer is congenitally unable to tell the truth and that is why we call what he writes fiction.', 'William Faulkner'),
(5, 'A fool''s brain digests philosophy into folly, science into superstition, and art into pedantry. Hence University education.', 'G. B. Shaw'),
(6, 'A great many people think they are thinking when they are merely rearranging their prejudices.', 'William James'),
(7, 'A good question is never answered. It is not a bolt to be tightened into place but a seed to be planted and to bear more seed toward the hope of greening the landscape of idea.', 'John Ciardi'),
(8, 'A synonym is a word you use when you can''t spell the word you first thought of.', 'Burt Bacharach'),
(9, 'A university is what a college becomes when the faculty loses interest in students.', 'John Ciardi'),
(10, 'Academic politics is the most vicious and bitter form of politics, because the stakes are so low.', 'Wallace Sayre'),
(11, 'Be careful when you bite into your hamburger.', 'Derek Bok'),
(12, 'Do not worry about which side your bread is buttered on: you eat BOTH sides.', 'Patrick'),
(13, 'Do not drink coffee in early A.M. It will keep you awake until noon.', 'John Deer'),
(14, 'Everything is worth precisely as much as a belch, the difference being that a belch is more satisfying.', 'Ingmar Bergman'),
(15, 'Food for thought is no substitute for the real thing.', 'Walt Kelly'),
(16, 'I''ll stay out of animals'' way if they''ll stay out of mine.', 'Roger Midnight'),
(17, 'I don''t care for the Sugar Smacks commercial. I don''t like the idea of a frog jumping on my Breakfast.', 'Lowell'),
(18, 'I don''t care where I sit as long as I get fed.', 'Calvin Trillin'),
(19, 'I have never been one to sacrifice my appetite on the altar of appearance.', 'A. M. Readyhough'),
(20, 'I have no doubt that it is a part of the destiny of the human race, in its gradual improvement, to leave off eating animals.', 'Thoreau'),
(21, 'I''ve been on a diet for two weeks and all I''ve lost is two weeks.', 'Totie Fields'),
(22, 'Kissing don''t last, cookery do.', 'George Meredith'),
(23, 'Last night I dreamed I ate a ten-pound marshmallow, and when I woke up the pillow was gone.', 'Tommy Cooper'),
(24, 'Life is like a bowl of soup with hairs floating on it.  You have to eat it nevertheless.', 'Flaubert'),
(25, 'Life is like a tin of sardines. We''re, all of us, looking for the key.', 'Beyond the Fringe'),
(26, 'Life is like an onion: you peel it off one layer at a time, and sometimes you weep.', 'Carl Sandburg'),
(27, 'Adam and Eve had many advantages, but the principal one was, that they escaped teething.', 'Mark Twain'),
(28, 'Anyone who uses the phrase "easy as taking candy from a baby" has never tried taking candy from a baby.', 'Robin Hood'),
(29, 'Children begin by loving their parents. After a time they judge them. Rarely, if ever, do they forgive them.', 'Oscar Wilde'),
(30, 'Children are unpredictable. You never know what inconsistency they''re going to catch you in next.', 'Franklin P. Jones'),
(31, 'Children begin by loving their parents. After a time they judge them.', 'Oscar Emelot'),
(32, 'Cleaning your house while your kids are still growing is like shoveling the walk before it stops snowing.', 'Phyllis Diller'),
(33, 'Delusions are often functional. A mother''s opinions about her children''s beauty, intelligence, goodness, et cetera ad nauseam, keep her from drowning them at birth.', 'Robert Heinlein'),
(34, 'Do not handicap your children by making their lives easy.', 'Robert Heinlein'),
(35, 'Having children is like having a bowling alley installed in your brain.', 'Martin Mull'),
(36, 'I called my parents the other night, but I forgot about the time difference. They''re still living in the fifties.', 'Strange de Jim'),
(37, 'I hate babies. They''re so human.', 'H. H. Munro'),
(38, 'I like men who have a future and women who have a past.', 'Oscar Wilde'),
(39, 'We live in an age when unnecessary things are our only necessities.', 'The Soul of Man'),
(40, 'In the depths of winter, I finally learned that within me there lay an invincible summer.', 'Albert Camus'),
(41, 'It is better to light a candle than curse the darkness.', 'Eleanor Roosevelt'),
(42, 'Plants are more courageous than almost all human beings an orange tree would rather die than produce lemons, whereas instead of dying the average person would rather be someone they are not.', 'Mokokoma Mokhonoana'),
(43, 'Show me that I m everywhere and get me home for tea.', 'George Harrison'),
(44, 'Knowing where the trap is that''s the first step in evading it.', 'Frank Herbert'),
(45, 'You cannot be truly humble, unless you truly believe that life can and will go on without you.', 'Mokokoma Mokhonoana'),
(46, 'Some people avoid thinking deeply in public, only because they are afraid of coming across as suicidal.', 'Mokokoma Mokhonoana'),
(47, 'I love children. Especially when they cry for then someone takes them away.', 'Nancy Mitford'),
(48, 'I tell ya, I was an ugly kid. I was so ugly that my dad kept the kid''s picture that came with the wallet he bought.', 'Rodney Dangerfield'),
(49, 'If pregnancy were a book they would cut the last two chapters.', 'Nora Ephron'),
(50, 'Absence in love is like water upon fire; a little quickens, but much extinguishes it.', 'Hannah More'),
(51, 'All the passions make us commit faults; love makes us commit the most ridiculous ones.', 'La Rochefoucauld'),
(52, 'Distrust all those who love you extremely upon a very slight acquaintance and without any visible reason.', 'Lord Chesterfield'),
(53, 'He who is in love with himself has at least this advantage he won''t encounter many rivals.', 'Georg Lichtenberg'),
(54, 'Hearts will never be practical until they can be made unbreakable.', 'The Wizard of Oz'),
(55, 'I am two fools, I know, for loving, and for saying so.', 'John Donne'),
(56, 'I can mend the break of day, heal a broken heart, and provide temporary relief to nymphomaniacs.', 'Larry Lee'),
(57, 'I love you, not only for what you are, but for what I am when I am with you.', 'Roy Croft'),
(58, 'I love you more than anything in this world. I don''t expect that will last.', 'Elvis Costello'),
(59, 'I think a relationship is like a shark. It has to constantly move forward it dies. Well, what we have on our hands here is a dead shark.', 'Woody Allen'),
(60, 'Do what thou wilt shall be the whole of the Law.', 'Aleister Crowley'),
(61, 'The first rule of magic is simple. Don''t waste your time waving your hands and hoping when a rock or a club will do.', 'McCloctnik the Lucid'),
(62, 'A bachelor is a selfish, undeserving guy who has cheated some woman out of a divorce.', 'Don Quinn'),
(63, 'A bachelor never quite gets over the idea that he is a thing of beauty and a boy for ever.', 'Helen Rowland'),
(64, 'A beautiful woman is a blessing from Heaven, but a good cigar is a smoke.', 'Kipling'),
(65, 'A boy can learn a lot from a dog, obedience, loyalty, and the importance of turning around three times before lying down.', 'Robert Benchley'),
(66, 'A diplomat is man who always remembers a woman''s birthday but never her age.', 'Robert Frost'),
(67, 'A lady is one who never shows her underwear unintentionally.', 'Lillian Day'),
(68, 'A man always remembers his first love with special tenderness, but after that begins to bunch them.', 'Mencken'),
(69, 'A man is like a rusty wheel on a rusty cart, He sings his song as he rattles along and then he falls apart.', 'Richard Thompson'),
(70, 'A city is a large community where people are lonesome together.', 'Herbert Prochnow'),
(71, 'Nobody knows what goes between his cold toes and his warm ears.', 'Roy Harper'),
(72, 'Nothing makes one so vain as being told that one is a sinner. Conscience makes egotists of us all.', 'Oscar Wilde'),
(73, 'Old age is the most unexpected of things that can happen to a man.', 'Trotsky'),
(74, 'One can never consent to creep when one feels an impulse to soar.', 'Helen Keller'),
(75, 'Go slowly to the entertainments of thy friends, but quickly to their misfortunes.', 'Chilo'),
(76, 'Genius may have its limitations, but stupidity is not thus handicapped.', 'Elbert Hubbard'),
(77, 'Growing old isn''t bad when you consider the alternatives.', 'Maurice Chevalier'),
(78, 'He is not only dull himself, he is the cause of dullness in others.', 'Samuel Johnson'),
(79, 'He had occasional flashes of silence that made his conversation perfectly delightful.', 'Sydney Smith'),
(80, 'He who wonders discovers that this in itself is wonder.', 'M. C. Escher'),
(81, 'I always pass on good advice. It is the only thing to do with it. It is never any good to oneself.', 'Oscar Wilde'),
(82, 'I am an optimist. It does not seem too much use being anything else.', 'Winston Churchill'),
(83, 'I can write better than anybody who can write faster, and I can write faster than anybody who can write better.', 'A. J. Liebling'),
(84, 'I can''t understand it. I can''t even understand the people who canunderstand it.', 'Queen Juliana'),
(85, 'I don''t know who my grandfather was. I am much more concerned to know what his grandson will be.', 'Abraham Lincoln'),
(86, 'Did you ever walk into a room and forget why you walked in?  I think that''s how dogs spend their lives.', 'Sue Murphy'),
(87, 'I loathe people who keep dogs. They are cowards who haven''t got the guts to bite people themselves.', 'August Strindberg'),
(88, 'No animal should ever jump on the dining room furniture unless absolutely certain he can hold his own in conversation.', 'Fran Lebowitz'),
(89, 'The main problem I have with cats is, they''re not dogs.', 'Kevin Cowherd'),
(90, 'It''s always sad when the fleas leave, because that means your dog is dead.', 'Wesley T. Williams'),
(91, 'A physicist is an atom''s way of knowing about atoms.', 'George Wald'),
(92, 'A sine curve goes off to infinity, or at least the end of the blackboard.', 'Prof. Steiner'),
(93, 'All great discoveries are made by mistake.', 'Kelly Young'),
(94, 'All laws are simulations of reality.', 'John C. Lilly'),
(95, 'All theoretical chemistry is really physics; and all theoretical chemists know it.', 'Richard P. Feynman'),
(96, 'Always think of something new this helps you forget your last rotten idea.', 'Seth Frankel'),
(97, 'An age is called Dark not because the light fails to shine, but because people refuse to see it.', 'James Michener'),
(98, 'An egghead is one who stands firmly on both feet, in mid-air, on both sides of an issue.', 'Homer Ferguson'),
(99, 'Any sufficiently advanced technology is indistinguishable from magic.', 'Arthur C. Clarke'),
(100, 'Artificial intelligence has the same relation to intelligence as artificial flowers have to flowers.', 'David Parnas'),
(101, 'All bridge hands are equally likely, but some are more equally likely than others.', 'Alan Truscott');